import type { DemoWorkspace } from './types'

export function createDemoWorkspace(): DemoWorkspace {
  return {
    version: 1,
    onboardingCompleted: false,
    workspaceName: '我的职业证据台',
    sources: [
      {
        id: 'source-resume',
        name: '现有简历.pdf',
        kind: 'resume',
        status: 'ready',
        selectedAt: '2026-08-28T09:20:00.000Z',
        size: 286_400,
      },
      {
        id: 'source-project',
        name: '校园项目复盘.docx',
        kind: 'project',
        status: 'review',
        selectedAt: '2026-08-28T09:22:00.000Z',
        size: 94_200,
      },
    ],
    facts: [
      {
        id: 'fact-research',
        category: 'experience',
        statement: '为校园二手交易小程序完成 18 名学生的访谈与可用性测试',
        detail: '负责访谈提纲、招募、记录和洞察归纳，原始记录位于项目复盘第 3 节。',
        status: 'verified',
        confidence: 1,
        sourceIds: ['source-project'],
        restricted: false,
      },
      {
        id: 'fact-flow',
        category: 'result',
        statement: '推动团队将发布流程从 7 步缩短到 4 步',
        detail: '数字来自产品迭代前后流程图，尚需确认是否为最终上线版本。',
        status: 'proposed',
        confidence: 0.82,
        sourceIds: ['source-project'],
        restricted: false,
      },
      {
        id: 'fact-sql',
        category: 'skill',
        statement: '使用 SQL 完成课程项目中的留存分析',
        detail: '当前证据只能证明项目使用经历，不能推断为“精通 SQL”。',
        status: 'verified',
        confidence: 1,
        sourceIds: ['source-resume'],
        restricted: false,
      },
      {
        id: 'fact-campus',
        category: 'preference',
        statement: '优先考虑北京、上海、杭州的产品与用户研究岗位',
        detail: '这是求职偏好，不会默认写入公开简历。',
        status: 'verified',
        confidence: 1,
        sourceIds: [],
        restricted: true,
      },
    ],
    jobs: [
      {
        id: 'job-1',
        company: '北辰智造',
        title: '用户研究员（校招）',
        location: '上海',
        source: '手动粘贴 JD',
        capturedAt: '2026-08-30T14:10:00.000Z',
        requirements: [
          {
            id: 'req-1',
            label: '独立设计并执行用户研究',
            importance: 'required',
            coverage: 'supported',
            factIds: ['fact-research'],
            rationale: '有完整访谈与可用性测试证据。',
          },
          {
            id: 'req-2',
            label: '将洞察转化为产品改进',
            importance: 'required',
            coverage: 'partial',
            factIds: ['fact-flow'],
            rationale: '有流程改进候选事实，但数字尚未核验。',
          },
          {
            id: 'req-3',
            label: '熟悉定量研究工具',
            importance: 'preferred',
            coverage: 'partial',
            factIds: ['fact-sql'],
            rationale: '只有一次课程项目证据，尚不能证明熟练度。',
          },
          {
            id: 'req-4',
            label: '有消费硬件研究经验',
            importance: 'preferred',
            coverage: 'missing',
            factIds: [],
            rationale: '个人档案中暂未找到相关证据。',
          },
        ],
      },
      {
        id: 'job-2',
        company: '远岫机器人',
        title: 'AI 产品经理',
        location: '杭州',
        source: '导入岗位快照',
        capturedAt: '2026-08-29T11:30:00.000Z',
        requirements: [
          {
            id: 'req-5',
            label: '用户需求分析与产品方案设计',
            importance: 'required',
            coverage: 'supported',
            factIds: ['fact-research', 'fact-flow'],
            rationale: '研究与流程改进可以共同支持该要求。',
          },
          {
            id: 'req-6',
            label: 'AI 产品实践经验',
            importance: 'required',
            coverage: 'missing',
            factIds: [],
            rationale: '档案中没有可验证的 AI 产品经历。',
          },
        ],
      },
    ],
    selectedJobId: 'job-1',
    resumeClaims: [
      {
        id: 'claim-summary',
        section: 'summary',
        text: '关注用户行为与产品决策的应届生，拥有从研究设计到洞察落地的项目实践。',
        sourceFactIds: ['fact-research'],
        included: true,
      },
      {
        id: 'claim-research',
        section: 'project',
        text: '独立完成 18 名学生访谈与可用性测试，归纳关键阻碍并推动发布流程优化。',
        sourceFactIds: ['fact-research', 'fact-flow'],
        included: true,
      },
      {
        id: 'claim-sql',
        section: 'skill',
        text: 'SQL：用于课程项目留存分析。',
        sourceFactIds: ['fact-sql'],
        included: true,
      },
    ],
    applications: [
      {
        id: 'application-1',
        company: '北辰智造',
        title: '用户研究员（校招）',
        stage: 'tailored',
        updatedAt: '今天 14:20',
      },
      {
        id: 'application-2',
        company: '远岫机器人',
        title: 'AI 产品经理',
        stage: 'analyzed',
        updatedAt: '昨天 18:40',
      },
      {
        id: 'application-3',
        company: '澄明教育',
        title: '增长产品经理',
        stage: 'interview',
        updatedAt: '8 月 28 日',
      },
    ],
    inbox: [
      {
        id: 'thread-1',
        company: '北辰智造',
        title: '用户研究员（校招）',
        sender: '招聘经理 林女士',
        receivedAt: '今天 10:24',
        message: '你好，可以介绍一下你最近一次把研究洞察转化为产品改进的经历吗？',
        suggestedReply:
          '您好，我在校园二手交易项目中完成了 18 名学生访谈与可用性测试，并据此推动团队简化发布流程。我可以进一步说明研究过程与我的具体贡献。',
        draft: '',
        state: 'needs_review',
      },
    ],
    privacy: {
      allowAiForVerifiedFacts: true,
      allowAiForPrivateFacts: false,
      diagnosticsEnabled: false,
    },
    interviewNotes: [],
    codexMode: 'not_connected',
  }
}
